dist: trusty

language: minimal

env:
  global:
    - VERSION="2019-10-04"
    - DOCKER_REPOSITORY="$DOCKER_USERNAME/hol-light"

jobs:
  include:
    - stage: Build image "environment"
      env: TAG=environment
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export TOPDIR=$(pwd)
      script: bash -e "$TOPDIR/build-image.sh"
    - stage: Build image "hol-light"
      env: TAG=hol-light
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export TOPDIR=$(pwd)
      script: bash -e "$TOPDIR/build-image.sh"
    - stage: Test docker images
      env:
        include:
          - TAG=environment
          - TAG=hol-light
      script:
        - echo "Testing $DOCKER_REPOSITORY:$TAG"
        - docker run --rm "$DOCKER_REPOSITORY:$TAG" ocamlc -version
        - if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ];
          then
            export BRANCH="$TRAVIS_BRANCH";
          else
            export BRANCH="$TRAVIS_PULL_REQUEST_BRANCH";
          fi
        - echo "Branch is $BRANCH"
        - if [ "$BRANCH" == "master" ];
          then
            docker tag hol-light "$DOCKER_REPOSITORY:latest"
            && docker push "$DOCKER_REPOSITORY:latest"
            && echo "New latest image sent";
          else
            echo "Do not send new latest image";
          fi
