dist: trusty

language: minimal

env:
  global:
    - VERSION="2019-10-04"
    - DOCKER_REPOSITORY="$DOCKER_USERNAME/hol-light"

jobs:
  include:
    - stage: Build docker images
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export TOPDIR=$(pwd)
      script:
        - ls -l
        - cat "$TOPDIR/build-image.sh"
        -    export TAG=environment && bash -e "$TOPDIR/build-image.sh"
          && export TAG=hol-light && bash -e "$TOPDIR/build-image.sh"
        - if [ "$DOCKER_IMAGE_BRANCH" == "$master" ];
          then
            docker tag hol-light "$DOCKER_REPOSITORY:latest";
            docker push "$DOCKER_REPOSITORY:latest";
          fi
    - stage: Test docker image
      script:
        - TAG=environment
        - echo "Testing $DOCKER_REPOSITORY:$TAG"
        - docker run --rm "$DOCKER_REPOSITORY:$TAG" ocamlc -version
      script:
        - TAG=hol-light
        - echo "Testing $DOCKER_REPOSITORY:$TAG"
        - docker run --rm "$DOCKER_REPOSITORY:$TAG" ocamlc -version
