dist: trusty
language: minimal

jobs:
  include:
    - stage: Build docker image.
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker pull $DOCKER_USERNAME/hol-light-environment:latest
      - docker build --cache-from $DOCKER_USERNAME/hol-light-environment:latest -t hol-light-environment .
      - docker tag hol-light-environment "$DOCKER_USERNAME"/hol-light-environment
      - docker push "$DOCKER_USERNAME"/hol-light-environment
    - stage: Test docker image.
      script: docker run --rm $DOCKER_USERNAME/hol-light-environment cat hello.txt
