dist: trusty

language: minimal

env:
  global:
    - VERSION="2019-10-04"
    - DOCKER_REPOSITORY="$DOCKER_USERNAME/hol-light"

jobs:
  include:
    - stage: Build image "environment"
      env: TAG=environment
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export TOPDIR=$(pwd)
      script: bash -e "$TOPDIR/build-image.sh"
    - stage: Build image "hol-light"
      env: TAG=hol-light
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export TOPDIR=$(pwd)
      script: bash -e "$TOPDIR/build-image.sh"
    - stage: Test docker images
      env:
        include:
          - TAG=environment
          - TAG=hol-light
      script:
        - echo "Testing $DOCKER_REPOSITORY:$TAG"
        - docker run --rm "$DOCKER_REPOSITORY:$TAG" ocamlc -version
        - echo "Push the new image"
        - env
        - if [ "$TRAVIS_BRANCH" == "master" ];
          then
            echo "Tag the image";
            docker tag hol-light "$DOCKER_REPOSITORY:latest";
            echo "Push the image";
            docker push "$DOCKER_REPOSITORY:latest";
            echo "New latest image sent";
          else
            echo "Do not send new latest image";
          fi
