# Example from Travis documentation
# https://docs.travis-ci.com/user/build-stages/share-docker-image/

dist: trusty
language: minimal

jobs:
  include:
    - stage: build docker image
      script: bash -e travis-build-image.sh
    - stage: test 1
      script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
    - stage: test 2
      script: bash -e travis-test-2.sh
